version: "3"

name: php-commerce

services:
  apache:
    image: devilbox/apache-2.4
    container_name: apache
    restart: unless-stopped
    ports:
      - 3000:80
      - 447:443
    networks:
      - net
    volumes:
      - ./www:/var/www/default 
      - ./config/php.ini:/etc/php-custom.d/php.ini
    env_file:
      - .env.apache
    extra_hosts:
      - host.docker.internal:host-gateway

  php-fpm:
    image: devilbox/php-fpm:8.2-work
    container_name: php8.2
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./www:/var/www/default
      - ./config/php.ini:/etc/php-custom.d/php.ini
    environment:
      - DEBUG_ENTRYPOINT=2
      - TIMEZONE=Asia/Kuala_Lumpur
      - XDEBUG_CONFIG="client_host=host.docker.internal remote_port=9003"

networks:
  net:
    driver: bridge